version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 10
    assignees:
      - pmmmwh
    labels:
      - dependencies
    groups:
      babel:
        patterns:
          - '@babel/*'
      commitlint:
        patterns:
          - '@commitlint/*'
      jest:
        patterns:
          - '@jest/*'
          - 'jest'
          - 'jest-*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
    versioning-strategy: widen
